[package]
name = "concurrency"
version = "0.1.0"
authors = ["thomas.spencer@codurance.com <thomas.spencer@codurance.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
